#!/bin/bash
cd "$('dirname' '--' "${0}")"
'g++' './AnalyzeLines_CSV.cc' '-Ofast' '-static' '-mtune=native' '-march=native' '-o' './AnalyzeLines_CSV.exe'
'g++' './AnalyzeLines_TSV.cc' '-Ofast' '-static' '-mtune=native' '-march=native' '-o' './AnalyzeLines_TSV.exe'
exit '0'
