.PHONY all: AnalyzeLines_CSV.exe AnalyzeLines_TSV.exe csv_2_null.exe csv_2_tsv.exe NewAnalyzeCSV.exe NewAnalyzeTSV.exe NewSimpleAnalyzeCSV.exe NewSimpleAnalyzeTSV.exe 

AnalyzeLines_CSV.exe: ./compile AnalyzeLines_CSV.cc
	./compile AnalyzeLines_CSV.cc
AnalyzeLines_TSV.exe: ./compile AnalyzeLines_TSV.cc
	./compile AnalyzeLines_TSV.cc
csv_2_null.exe: ./compile csv_2_null.cc
	./compile csv_2_null.cc
csv_2_tsv.exe: ./compile csv_2_tsv.cc
	./compile csv_2_tsv.cc
NewAnalyzeCSV.exe: ./compile NewAnalyzeCSV.cc
	./compile NewAnalyzeCSV.cc
NewAnalyzeTSV.exe: ./compile NewAnalyzeTSV.cc
	./compile NewAnalyzeTSV.cc
NewSimpleAnalyzeCSV.exe: ./compile NewSimpleAnalyzeCSV.cc
	./compile NewSimpleAnalyzeCSV.cc
NewSimpleAnalyzeTSV.exe: ./compile NewSimpleAnalyzeTSV.cc
	./compile NewSimpleAnalyzeTSV.cc
