#!/bin/bash
'sed' 's@^#include <TH2.h>$@@g;s@^#include <TStyle.h>$@@g;s@^#include <TCanvas.h>$@@g;s@^#include <TROOT.h>$@@g;s@^#include <TChain.h>$@@g;s@^#include <TFile.h>$@@g;s@^#include "TClonesArray.h"$@@g;s@^#include "TObject.h"$@@g;s@^#include "classes/DelphesClasses.h"$@@g' "${1}" '-i'
'grep' '-v' "^$" "${1}" > "${1}.tmp"
'mv' "${1}.tmp" "${1}"
exit '0'
