STEP8_CNN_AE_RESPONSE_PLOT_AND_TMVAROOT::CNN_LOSS_ROC::WORK();
STEP5_PLOTLOSSES_TMVAROOT::MakeTMVARoot();
STEP5_PLOTLOSSES_TMVAROOT::MakeTMVARoot_HUGE();

//STEP5_PLOTLOSSES_TMVAROOT::PlotLosses();
//STEP5_PLOTLOSSES_TMVAROOT::PlotLosses_CNN();

//STEP10_2D_MASS_ERROR::PLOT_LOSS_MASS::WORK_QCD_TEST();
//STEP10_2D_MASS_ERROR::PLOT_LOSS_MASS::HUGE_DENCE_QCD();
//STEP10_2D_MASS_ERROR::PLOT_LOSS_MASS::CNN_QCD_TEST();
