#!/bin/bash
cd "$('dirname' '--' "${0}")/install"
'mkdir' '-pv' '--' '/usr/local'
'cp' '-vaspf' '--' "$('/bin/pwd')" '/usr/local/'
cd '/usr/local/install'
'cp' '-valpf' '.' '../'
cd '../'
'rm' '-vrf' '--' './install'
exit '0'
